version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - internal
    volumes:
      - mongodb_data:/data/db

  # redis:
  #   image: redis
  #   container_name: redis
  #   networks:
  #     - internal

  likes-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: likes-microservice
    networks:
      - internal
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
      # - redis
    environment:
      PORT: ${PORT}
      MONGODB_URI: mongodb://mongodb:27017/likesDB
      # REDIS_URL: redis://redis:6379

networks:
  internal:
    driver: bridge

volumes:
  mongodb_data:
