version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
  likes-microservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: likes-microservice
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - redis
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/likesDB
      REDIS_URL: redis://redis:6379
